replicaCount: 2

image:
  repository: 112715105011/hello-java-spring-boot
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080
  name: ui
  targetport: 8080
  
containers:
  name: react-ui
  
