replicaCount: 2

image:
  repository: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
  pullPolicy: IfNotPresent
  tag: 

service:
  type: ClusterIP
  port: 8080
  name: ui
  targetport: 8080
  
containers:
  name: react-ui
  
