replicaCount: 2

image:
  repository: javaee/springdemo
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080
  name: ui
  targetport: 8080
  
containers:
  name: react-ui
  
