apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "oc-deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oc-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oc-deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
           - secretRef:
               name: my-secret
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
